export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  CASHIER: 'CASHIER',
  PROCUREMENT_OFFICER: 'PROCUREMENT_OFFICER',
  DELIVERY_SUPERVISOR: 'DELIVERY_SUPERVISOR',
  RIDER: 'RIDER',
};

export const ALL_ROLES = Object.values(ROLES);