export const NAV_ITEMS = [
  { label: 'Dashboard', path: '/', icon: 'LayoutDashboard', permission: 'view_reports' },
  { label: 'Livestock & Herd', path: '/animals', icon: 'Beef', permission: 'manage_livestock' },
  { label: 'Milk Yield Entry', path: '/yield', icon: 'Milk', permission: 'record_yield' },
  { label: 'Suppliers', path: '/suppliers', icon: 'Truck', permission: 'manage_suppliers' },
  { label: 'Milk Procurement', path: '/procurement', icon: 'FlaskConical', permission: 'manage_procurement' },
  { label: 'Products & Pricing', path: '/products', icon: 'Package', permission: 'manage_products' },
  { label: 'POS Counter', path: '/pos', icon: 'Calculator', permission: 'pos_sales' },
  { label: 'Sales History', path: '/sales', icon: 'Receipt', permission: 'view_sales' },
  { label: 'Customers', path: '/customers', icon: 'Users', permission: 'manage_customers' },
  { label: 'Khata Ledger', path: '/khata', icon: 'BookOpen', permission: 'manage_khata' },
  { label: 'Subscriptions', path: '/subscriptions', icon: 'CalendarSync', permission: 'manage_subscriptions' },
  { label: 'Deliveries & Routes', path: '/deliveries', icon: 'Bike', permission: 'manage_deliveries' },
  { label: 'Processing & BOM', path: '/processing', icon: 'Factory', permission: 'manage_processing' },
  { label: 'Inventory', path: '/inventory', icon: 'Boxes', permission: 'view_inventory' },
  { label: 'Expenses', path: '/expenses', icon: 'Wallet', permission: 'manage_expenses' },
  { label: 'Daily Closing', path: '/closing', icon: 'CheckCircle2', permission: 'submit_daily_closing' },
  { label: 'Reports', path: '/reports', icon: 'BarChart3', permission: 'view_reports' },
  { label: 'Audit Logs', path: '/audit', icon: 'ShieldCheck', permission: 'view_audit_logs' },
  { label: 'Staff Users', path: '/users', icon: 'UserCog', permission: 'manage_users' },
  { label: 'Settings', path: '/settings', icon: 'Settings', permission: 'manage_settings' },
];